apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-generation-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: text-generation
  template:
    metadata:
      labels:
        app: text-generation
    spec:
      containers:
        - name: text-generation-container
          image: ghcr.io/huggingface/text-generation-inference:1.0.1
          ports:
            - containerPort: 80
          volumeMounts:
            - name: data-volume
              mountPath: /data
          env:
            - name: HUGGING_FACE_HUB_TOKEN
              value: "<your-token>"
          args:
            - "--max-input-length=3900"
            - "--max-total-tokens=4096"
            - "--rope-scaling=dynamic"
            - "--rope-factor=2.0"
            - "--model-id=TheBloke/Chronos-Hermes-13B-SuperHOT-8K-fp16"
          resources:
            limits:
              nvidia.com/gpu: 1
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-pvc
